name: GitHub Contribution Snake

on:
  # Esecuzione automatica ogni giorno a mezzanotte UTC
  schedule:
    - cron: "0 0 * * *"

  # Permette di avviare il workflow manualmente
  workflow_dispatch:

  # Attiva il workflow quando viene fatto un push su `main`
  push:
    branches:
      - main

jobs:
  generate_snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Clona il repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Genera la GIF animata delle contribuzioni
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/contribution-snake.svg
            dist/contribution-snake-dark.svg?palette=github-dark
            dist/contribution-ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

        env:
          GITHUB_TOKEN: ${{ secrets.LOL }}

      # Step 3: Pubblica i file generati nel branch `output`
      - name: Deploy Generated Files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.LOL}}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Automated update: Contribution Snake animation"
